"""initial_migration_all_18_tables

Revision ID: c10e6a475783
Revises: 
Create Date: 2026-02-27 17:48:16.642026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c10e6a475783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'admin_role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_admin_name'), table_name='audit_logs')
    op.drop_index(op.f('idx_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_name'), 'audit_logs', ['admin_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'user_agent')
    op.alter_column('communication_history', 'sent_by_role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_index(op.f('idx_investor_id'), table_name='communication_history')
    op.drop_index(op.f('idx_sent_at'), table_name='communication_history')
    op.drop_index(op.f('idx_series_name'), table_name='communication_history')
    op.drop_index(op.f('idx_status'), table_name='communication_history')
    op.drop_index(op.f('idx_type'), table_name='communication_history')
    op.create_index(op.f('ix_communication_history_investor_id'), 'communication_history', ['investor_id'], unique=False)
    op.create_index(op.f('ix_communication_history_sent_at'), 'communication_history', ['sent_at'], unique=False)
    op.create_index(op.f('ix_communication_history_status'), 'communication_history', ['status'], unique=False)
    op.create_index(op.f('ix_communication_history_type'), 'communication_history', ['type'], unique=False)
    op.drop_column('communication_history', 'created_at')
    op.drop_index(op.f('idx_active'), table_name='communication_templates')
    op.drop_index(op.f('idx_type'), table_name='communication_templates')
    op.create_index(op.f('ix_communication_templates_is_active'), 'communication_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_communication_templates_type'), 'communication_templates', ['type'], unique=False)
    op.add_column('compliance_documents', sa.Column('compliance_status_id', sa.Integer(), nullable=False))
    op.add_column('compliance_documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.alter_column('compliance_documents', 'file_size',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('compliance_documents', 'uploaded_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index(op.f('idx_active'), table_name='compliance_documents')
    op.drop_index(op.f('idx_series_category'), table_name='compliance_documents')
    op.drop_index(op.f('idx_uploaded_at'), table_name='compliance_documents')
    op.create_index(op.f('ix_compliance_documents_compliance_status_id'), 'compliance_documents', ['compliance_status_id'], unique=False)
    op.create_index(op.f('ix_compliance_documents_series_id'), 'compliance_documents', ['series_id'], unique=False)
    op.drop_constraint(op.f('compliance_documents_ibfk_2'), 'compliance_documents', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_documents', 'series_compliance_status', ['compliance_status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('compliance_documents', 'description')
    op.drop_column('compliance_documents', 'month')
    op.drop_column('compliance_documents', 's3_bucket')
    op.drop_column('compliance_documents', 'content_type')
    op.drop_column('compliance_documents', 'master_item_id')
    op.drop_column('compliance_documents', 's3_url')
    op.drop_column('compliance_documents', 'year')
    op.drop_column('compliance_documents', 'document_title')
    op.drop_column('compliance_documents', 's3_key')
    op.drop_column('compliance_documents', 'deleted_at')
    op.drop_column('compliance_documents', 'is_active')
    op.drop_column('compliance_documents', 'deleted_by')
    op.add_column('compliance_master_items', sa.Column('item_name', sa.String(length=255), nullable=False))
    op.add_column('compliance_master_items', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('compliance_master_items', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('compliance_master_items', 'frequency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('Monthly', 'Quarterly', 'Half_Yearly', 'Yearly', 'One_Time', name='compliancefrequencyenum'),
               nullable=False)
    op.drop_index(op.f('idx_active'), table_name='compliance_master_items')
    op.drop_index(op.f('idx_display_order'), table_name='compliance_master_items')
    op.drop_index(op.f('idx_section'), table_name='compliance_master_items')
    op.create_index(op.f('ix_compliance_master_items_category'), 'compliance_master_items', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_master_items_frequency'), 'compliance_master_items', ['frequency'], unique=False)
    op.drop_table_comment(
        'compliance_master_items',
        existing_comment='Master template of 42 compliance items - shared across all series',
        schema=None
    )
    op.drop_column('compliance_master_items', 'legal_reference')
    op.drop_column('compliance_master_items', 'display_order')
    op.drop_column('compliance_master_items', 'title')
    op.drop_column('compliance_master_items', 'section')
    op.add_column('grievances', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('grievances', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.alter_column('grievances', 'investor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('grievances', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('grievances', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('grievances', 'status',
               existing_type=mysql.ENUM('pending', 'in-progress', 'resolved', 'closed', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('open', 'in_progress', 'resolved', 'closed', name='grievancestatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('grievances', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('grievances', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('grievances', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('grievances', 'resolved_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('grievance_id'), table_name='grievances')
    op.drop_index(op.f('idx_category'), table_name='grievances')
    op.drop_index(op.f('idx_created_at'), table_name='grievances')
    op.drop_index(op.f('idx_grievance_type'), table_name='grievances')
    op.drop_index(op.f('idx_investor_id'), table_name='grievances')
    op.drop_index(op.f('idx_priority'), table_name='grievances')
    op.drop_index(op.f('idx_series_id'), table_name='grievances')
    op.drop_index(op.f('idx_status'), table_name='grievances')
    op.create_index(op.f('ix_grievances_grievance_type'), 'grievances', ['grievance_type'], unique=False)
    op.create_index(op.f('ix_grievances_investor_id'), 'grievances', ['investor_id'], unique=False)
    op.create_index(op.f('ix_grievances_priority'), 'grievances', ['priority'], unique=False)
    op.create_index(op.f('ix_grievances_series_id'), 'grievances', ['series_id'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_foreign_key(None, 'grievances', 'ncd_series', ['series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'grievances', 'investors', ['investor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('grievances', 'grievance_id')
    op.drop_column('grievances', 'investor_name')
    op.drop_column('grievances', 'created_by_role')
    op.drop_column('grievances', 'resolution_comment')
    op.drop_column('grievances', 'trustee_name')
    op.drop_column('grievances', 'is_active')
    op.drop_column('grievances', 'series_name')
    op.add_column('interest_payouts', sa.Column('investment_id', sa.Integer(), nullable=False))
    op.add_column('interest_payouts', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.add_column('interest_payouts', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('interest_payouts', sa.Column('processed_by', sa.String(length=255), nullable=True))
    op.add_column('interest_payouts', sa.Column('processed_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('interest_payouts', 'payout_date',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               comment=None,
               existing_comment='e.g., 15-Feb-2026',
               existing_nullable=False)
    op.alter_column('interest_payouts', 'amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment=None,
               existing_comment='Interest amount in rupees',
               existing_nullable=False)
    op.alter_column('interest_payouts', 'status',
               existing_type=mysql.ENUM('Paid', 'Pending', 'Scheduled'),
               type_=sa.Enum('pending', 'completed', 'failed', name='payoutstatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Scheduled'"))
    op.drop_index(op.f('idx_investor'), table_name='interest_payouts')
    op.drop_index(op.f('idx_payout_month'), table_name='interest_payouts')
    op.drop_index(op.f('idx_series'), table_name='interest_payouts')
    op.drop_index(op.f('idx_status'), table_name='interest_payouts')
    op.drop_index(op.f('unique_payout'), table_name='interest_payouts')
    op.create_index(op.f('ix_interest_payouts_investor_id'), 'interest_payouts', ['investor_id'], unique=False)
    op.create_index(op.f('ix_interest_payouts_payout_date'), 'interest_payouts', ['payout_date'], unique=False)
    op.create_index(op.f('ix_interest_payouts_series_id'), 'interest_payouts', ['series_id'], unique=False)
    op.create_index(op.f('ix_interest_payouts_status'), 'interest_payouts', ['status'], unique=False)
    op.create_foreign_key(None, 'interest_payouts', 'investments', ['investment_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'interest_payouts',
        existing_comment='Interest payout records for investors',
        schema=None
    )
    op.drop_column('interest_payouts', 'paid_date')
    op.drop_column('interest_payouts', 'payout_month')
    op.drop_column('interest_payouts', 'is_active')
    op.add_column('investments', sa.Column('units', sa.Integer(), nullable=False))
    op.add_column('investments', sa.Column('investment_date', sa.Date(), nullable=False))
    op.add_column('investments', sa.Column('payment_mode', sa.String(length=50), nullable=True))
    op.add_column('investments', sa.Column('transaction_reference', sa.String(length=255), nullable=True))
    op.alter_column('investments', 'date_transferred',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('investments', 'date_received',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('investments', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investments', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_investor_id'), table_name='investments')
    op.drop_index(op.f('idx_series_id'), table_name='investments')
    op.drop_index(op.f('idx_status'), table_name='investments')
    op.create_index(op.f('ix_investments_investment_date'), 'investments', ['investment_date'], unique=False)
    op.create_index(op.f('ix_investments_investor_id'), 'investments', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investments_series_id'), 'investments', ['series_id'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.drop_column('investments', 'payment_document_path')
    op.drop_column('investments', 'exit_date')
    op.add_column('investor_documents', sa.Column('uploaded_by', sa.String(length=255), nullable=True))
    op.alter_column('investor_documents', 'file_size',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('investor_documents', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_document_type'), table_name='investor_documents')
    op.drop_index(op.f('idx_investor_id'), table_name='investor_documents')
    op.create_index(op.f('ix_investor_documents_document_type'), 'investor_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_investor_documents_investor_id'), 'investor_documents', ['investor_id'], unique=False)
    op.add_column('investor_series', sa.Column('exit_date', sa.Date(), nullable=True))
    op.add_column('investor_series', sa.Column('exit_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.alter_column('investor_series', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('active', 'exited', 'matured', name='investorseriesstatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('investor_series', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investor_series', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_investor_id'), table_name='investor_series')
    op.drop_index(op.f('idx_series_id'), table_name='investor_series')
    op.drop_index(op.f('unique_investor_series'), table_name='investor_series')
    op.create_index(op.f('ix_investor_series_investor_id'), 'investor_series', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investor_series_series_id'), 'investor_series', ['series_id'], unique=False)
    op.create_index(op.f('ix_investor_series_status'), 'investor_series', ['status'], unique=False)
    op.drop_column('investor_series', 'total_invested')
    op.drop_column('investor_series', 'last_investment_date')
    op.drop_column('investor_series', 'investment_count')
    op.drop_column('investor_series', 'first_investment_date')
    op.add_column('investors', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('investors', sa.Column('aadhar_number', sa.String(length=20), nullable=True))
    op.add_column('investors', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('investors', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('investors', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('investors', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('investors', sa.Column('account_holder_name', sa.String(length=255), nullable=True))
    op.add_column('investors', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('investors', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('investors', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
    op.alter_column('investors', 'bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('investors', 'account_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('investors', 'ifsc_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('investors', 'kyc_status',
               existing_type=mysql.ENUM('Pending', 'Completed', 'Rejected', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('pending', 'verified', 'rejected', name='kycstatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
    op.alter_column('investors', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investors', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_email'), table_name='investors')
    op.drop_index(op.f('idx_investor_id'), table_name='investors')
    op.drop_index(op.f('idx_kyc_status'), table_name='investors')
    op.drop_index(op.f('idx_status'), table_name='investors')
    op.drop_index(op.f('investor_id'), table_name='investors')
    op.create_index(op.f('ix_investors_email'), 'investors', ['email'], unique=False)
    op.create_index(op.f('ix_investors_investor_id'), 'investors', ['investor_id'], unique=True)
    op.create_index(op.f('ix_investors_kyc_status'), 'investors', ['kyc_status'], unique=False)
    op.create_index(op.f('ix_investors_phone'), 'investors', ['phone'], unique=False)
    op.create_index(op.f('ix_investors_status'), 'investors', ['status'], unique=False)
    op.drop_column('investors', 'nominee_relationship')
    op.drop_column('investors', 'nominee_address')
    op.drop_column('investors', 'dob')
    op.drop_column('investors', 'nominee_name')
    op.drop_column('investors', 'date_joined')
    op.drop_column('investors', 'aadhaar')
    op.drop_column('investors', 'nominee_mobile')
    op.drop_column('investors', 'residential_address')
    op.drop_column('investors', 'pan')
    op.drop_column('investors', 'total_investment')
    op.drop_column('investors', 'nominee_email')
    op.drop_column('investors', 'source_of_funds')
    op.drop_column('investors', 'occupation')
    op.drop_column('investors', 'is_active')
    op.drop_column('investors', 'correspondence_address')
    op.add_column('ncd_series', sa.Column('total_amount', sa.DECIMAL(precision=20, scale=2), nullable=False))
    op.add_column('ncd_series', sa.Column('minimum_investment', sa.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('ncd_series', sa.Column('maximum_investment', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('ncd_series', sa.Column('lock_in_period', sa.Integer(), nullable=True))
    op.add_column('ncd_series', sa.Column('terms_conditions', sa.Text(), nullable=True))
    op.alter_column('ncd_series', 'interest_rate',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('ncd_series', 'face_value',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('ncd_series', 'interest_frequency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('Monthly', 'Quarterly', 'Half_Yearly', 'Yearly', name='interestfrequencyenum'),
               existing_nullable=False)
    op.alter_column('ncd_series', 'status',
               existing_type=mysql.ENUM('DRAFT', 'REJECTED', 'upcoming', 'accepting', 'active', 'matured', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('draft', 'pending_approval', 'approved', 'active', 'matured', 'closed', name='seriesstatusenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('ncd_series', 'security_type',
               existing_type=mysql.ENUM('Secured', 'Unsecured', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('ncd_series', 'credit_rating',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('ncd_series', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('ncd_series', 'approved_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ncd_series', 'approved_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('idx_dates'), table_name='ncd_series')
    op.drop_index(op.f('idx_is_active'), table_name='ncd_series')
    op.drop_index(op.f('idx_series_code'), table_name='ncd_series')
    op.drop_index(op.f('idx_status'), table_name='ncd_series')
    op.drop_index(op.f('name'), table_name='ncd_series')
    op.drop_index(op.f('series_code'), table_name='ncd_series')
    op.create_index(op.f('ix_ncd_series_issue_date'), 'ncd_series', ['issue_date'], unique=False)
    op.create_index(op.f('ix_ncd_series_maturity_date'), 'ncd_series', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_ncd_series_series_code'), 'ncd_series', ['series_code'], unique=True)
    op.create_index(op.f('ix_ncd_series_status'), 'ncd_series', ['status'], unique=False)
    op.drop_constraint(op.f('fk_rejected_by'), 'ncd_series', type_='foreignkey')
    op.drop_constraint(op.f('fk_last_modified_by'), 'ncd_series', type_='foreignkey')
    op.drop_constraint(op.f('fk_approved_by'), 'ncd_series', type_='foreignkey')
    op.drop_column('ncd_series', 'investors_size')
    op.drop_column('ncd_series', 'interest_payment_day')
    op.drop_column('ncd_series', 'subscription_end_date')
    op.drop_column('ncd_series', 'target_amount')
    op.drop_column('ncd_series', 'total_issue_size')
    op.drop_column('ncd_series', 'debenture_trustee_name')
    op.drop_column('ncd_series', 'rejected_by')
    op.drop_column('ncd_series', 'approval_notes')
    op.drop_column('ncd_series', 'subscription_start_date')
    op.drop_column('ncd_series', 'tenure')
    op.drop_column('ncd_series', 'min_subscription_percentage')
    op.drop_column('ncd_series', 'rejection_reason')
    op.drop_column('ncd_series', 'release_date')
    op.drop_column('ncd_series', 'last_modified_by')
    op.drop_column('ncd_series', 'lock_in_date')
    op.drop_column('ncd_series', 'min_investment')
    op.drop_column('ncd_series', 'series_start_date')
    op.drop_column('ncd_series', 'rejected_at')
    op.drop_column('ncd_series', 'last_modified_at')
    op.add_column('report_logs', sa.Column('generated_by', sa.String(length=255), nullable=False))
    op.add_column('report_logs', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('report_logs', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.alter_column('report_logs', 'report_type',
               existing_type=mysql.ENUM('PDF', 'Excel', 'CSV', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('report_logs', 'report_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_generated_at'), table_name='report_logs')
    op.drop_index(op.f('idx_report_date'), table_name='report_logs')
    op.drop_index(op.f('idx_report_name'), table_name='report_logs')
    op.drop_index(op.f('idx_report_type'), table_name='report_logs')
    op.drop_index(op.f('idx_status'), table_name='report_logs')
    op.drop_index(op.f('idx_user_date'), table_name='report_logs')
    op.drop_index(op.f('idx_user_id'), table_name='report_logs')
    op.create_index(op.f('ix_report_logs_generated_at'), 'report_logs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_report_logs_generated_by'), 'report_logs', ['generated_by'], unique=False)
    op.create_index(op.f('ix_report_logs_report_type'), 'report_logs', ['report_type'], unique=False)
    op.drop_constraint(op.f('report_logs_ibfk_1'), 'report_logs', type_='foreignkey')
    op.drop_column('report_logs', 'report_filters')
    op.drop_column('report_logs', 'record_count')
    op.drop_column('report_logs', 'user_role')
    op.drop_column('report_logs', 'user_name')
    op.drop_column('report_logs', 'file_size_kb')
    op.drop_column('report_logs', 'user_id')
    op.drop_column('report_logs', 'generation_time_ms')
    op.add_column('role_permissions', sa.Column('role_name', sa.String(length=50), nullable=False))
    op.add_column('role_permissions', sa.Column('permission_name', sa.String(length=100), nullable=False))
    op.add_column('role_permissions', sa.Column('is_granted', sa.Boolean(), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('role_permissions', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_role'), table_name='role_permissions')
    op.drop_index(op.f('idx_updated_at'), table_name='role_permissions')
    op.drop_index(op.f('unique_role'), table_name='role_permissions')
    op.create_index(op.f('ix_role_permissions_permission_name'), 'role_permissions', ['permission_name'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_name'), 'role_permissions', ['role_name'], unique=False)
    op.drop_column('role_permissions', 'permissions')
    op.drop_column('role_permissions', 'role')
    op.drop_column('role_permissions', 'updated_by')
    op.add_column('series_approvals', sa.Column('approver_name', sa.String(length=255), nullable=False))
    op.add_column('series_approvals', sa.Column('approver_role', sa.String(length=50), nullable=False))
    op.add_column('series_approvals', sa.Column('action', sa.Enum('approved', 'rejected', name='approval_action'), nullable=False))
    op.add_column('series_approvals', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('series_approvals', sa.Column('approved_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('idx_action_timestamp'), table_name='series_approvals')
    op.drop_index(op.f('idx_action_type'), table_name='series_approvals')
    op.drop_index(op.f('idx_series_action'), table_name='series_approvals')
    op.drop_index(op.f('idx_series_id'), table_name='series_approvals')
    op.drop_index(op.f('idx_user_id'), table_name='series_approvals')
    op.create_index(op.f('ix_series_approvals_approver_name'), 'series_approvals', ['approver_name'], unique=False)
    op.create_index(op.f('ix_series_approvals_series_id'), 'series_approvals', ['series_id'], unique=False)
    op.drop_constraint(op.f('series_approvals_ibfk_2'), 'series_approvals', type_='foreignkey')
    op.drop_column('series_approvals', 'ip_address')
    op.drop_column('series_approvals', 'user_agent')
    op.drop_column('series_approvals', 'new_status')
    op.drop_column('series_approvals', 'action_type')
    op.drop_column('series_approvals', 'action_timestamp')
    op.drop_column('series_approvals', 'user_role')
    op.drop_column('series_approvals', 'user_name')
    op.drop_column('series_approvals', 'approval_notes')
    op.drop_column('series_approvals', 'created_at')
    op.drop_column('series_approvals', 'changes_made')
    op.drop_column('series_approvals', 'user_id')
    op.drop_column('series_approvals', 'previous_status')
    op.drop_column('series_approvals', 'rejection_reason')
    op.add_column('series_compliance_status', sa.Column('compliance_item_id', sa.Integer(), nullable=False))
    op.add_column('series_compliance_status', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('series_compliance_status', sa.Column('completed_date', sa.Date(), nullable=True))
    op.add_column('series_compliance_status', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('series_compliance_status', sa.Column('completed_by', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_period'), table_name='series_compliance_status')
    op.drop_index(op.f('idx_series_status'), table_name='series_compliance_status')
    op.drop_index(op.f('idx_series_year_month'), table_name='series_compliance_status')
    op.drop_index(op.f('unique_series_item_month'), table_name='series_compliance_status')
    op.drop_index(op.f('unique_series_item_period'), table_name='series_compliance_status')
    op.create_index(op.f('ix_series_compliance_status_due_date'), 'series_compliance_status', ['due_date'], unique=False)
    op.create_index(op.f('ix_series_compliance_status_series_id'), 'series_compliance_status', ['series_id'], unique=False)
    op.create_index(op.f('ix_series_compliance_status_status'), 'series_compliance_status', ['status'], unique=False)
    op.drop_constraint(op.f('series_compliance_status_ibfk_2'), 'series_compliance_status', type_='foreignkey')
    op.create_foreign_key(None, 'series_compliance_status', 'compliance_master_items', ['compliance_item_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'series_compliance_status',
        existing_comment='Compliance status per series per month - like role_permissions pattern',
        schema=None
    )
    op.drop_column('series_compliance_status', 'submitted_by')
    op.drop_column('series_compliance_status', 'month')
    op.drop_column('series_compliance_status', 'title')
    op.drop_column('series_compliance_status', 'frequency')
    op.drop_column('series_compliance_status', 'master_item_id')
    op.drop_column('series_compliance_status', 'notes')
    op.drop_column('series_compliance_status', 'section')
    op.drop_column('series_compliance_status', 'year')
    op.drop_column('series_compliance_status', 'submitted_at')
    op.add_column('series_documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.alter_column('series_documents', 'file_size',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('series_documents', 'uploaded_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_index(op.f('idx_document_type'), table_name='series_documents')
    op.drop_index(op.f('idx_series_id'), table_name='series_documents')
    op.drop_index(op.f('unique_series_document'), table_name='series_documents')
    op.create_index(op.f('ix_series_documents_document_type'), 'series_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_series_documents_series_id'), 'series_documents', ['series_id'], unique=False)
    op.drop_column('series_documents', 's3_bucket')
    op.drop_column('series_documents', 'is_active')
    op.drop_column('series_documents', 's3_url')
    op.drop_column('series_documents', 's3_key')
    op.drop_column('series_documents', 'content_type')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('last_activity', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Enum('super_admin', 'admin', 'manager', 'viewer', 'investor', name='userroleenum'),
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('full_name'), table_name='users')
    op.drop_index(op.f('idx_email'), table_name='users')
    op.drop_index(op.f('idx_is_active'), table_name='users')
    op.drop_index(op.f('idx_user_id'), table_name='users')
    op.drop_index(op.f('idx_username'), table_name='users')
    op.drop_index(op.f('phone'), table_name='users')
    op.drop_index(op.f('user_id'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
    op.add_column('users', sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('idx_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('full_name'), 'users', ['full_name'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'manager', 'viewer', 'investor', name='userroleenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'hashed_password')
    op.add_column('series_documents', sa.Column('content_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'application/pdf'"), nullable=True))
    op.add_column('series_documents', sa.Column('s3_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.add_column('series_documents', sa.Column('s3_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False))
    op.add_column('series_documents', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('series_documents', sa.Column('s3_bucket', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_index(op.f('ix_series_documents_series_id'), table_name='series_documents')
    op.drop_index(op.f('ix_series_documents_document_type'), table_name='series_documents')
    op.create_index(op.f('unique_series_document'), 'series_documents', ['series_id', 'document_type'], unique=True)
    op.create_index(op.f('idx_series_id'), 'series_documents', ['series_id'], unique=False)
    op.create_index(op.f('idx_document_type'), 'series_documents', ['document_type'], unique=False)
    op.alter_column('series_documents', 'uploaded_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('series_documents', 'file_size',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('series_documents', 'file_path')
    op.add_column('series_compliance_status', sa.Column('submitted_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('series_compliance_status', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('series_compliance_status', sa.Column('section', mysql.ENUM('pre', 'post', 'recurring', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('series_compliance_status', sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('series_compliance_status', sa.Column('master_item_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('series_compliance_status', sa.Column('frequency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('series_compliance_status', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.add_column('series_compliance_status', sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('series_compliance_status', sa.Column('submitted_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.create_table_comment(
        'series_compliance_status',
        'Compliance status per series per month - like role_permissions pattern',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'series_compliance_status', type_='foreignkey')
    op.create_foreign_key(op.f('series_compliance_status_ibfk_2'), 'series_compliance_status', 'compliance_master_items', ['master_item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_series_compliance_status_status'), table_name='series_compliance_status')
    op.drop_index(op.f('ix_series_compliance_status_series_id'), table_name='series_compliance_status')
    op.drop_index(op.f('ix_series_compliance_status_due_date'), table_name='series_compliance_status')
    op.create_index(op.f('unique_series_item_period'), 'series_compliance_status', ['series_id', 'master_item_id', 'year', 'month'], unique=True)
    op.create_index(op.f('unique_series_item_month'), 'series_compliance_status', ['series_id', 'master_item_id', 'year', 'month'], unique=True)
    op.create_index(op.f('idx_series_year_month'), 'series_compliance_status', ['series_id', 'year', 'month'], unique=False)
    op.create_index(op.f('idx_series_status'), 'series_compliance_status', ['series_id', 'status'], unique=False)
    op.create_index(op.f('idx_period'), 'series_compliance_status', ['year', 'month'], unique=False)
    op.drop_column('series_compliance_status', 'completed_by')
    op.drop_column('series_compliance_status', 'remarks')
    op.drop_column('series_compliance_status', 'completed_date')
    op.drop_column('series_compliance_status', 'due_date')
    op.drop_column('series_compliance_status', 'compliance_item_id')
    op.add_column('series_approvals', sa.Column('rejection_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('series_approvals', sa.Column('previous_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('series_approvals', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('series_approvals', sa.Column('changes_made', mysql.JSON(), nullable=True))
    op.add_column('series_approvals', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('series_approvals', sa.Column('approval_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('series_approvals', sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('series_approvals', sa.Column('user_role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('series_approvals', sa.Column('action_timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('series_approvals', sa.Column('action_type', mysql.ENUM('APPROVED', 'REJECTED', 'EDITED', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('series_approvals', sa.Column('new_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('series_approvals', sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('series_approvals', sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True))
    op.create_foreign_key(op.f('series_approvals_ibfk_2'), 'series_approvals', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_series_approvals_series_id'), table_name='series_approvals')
    op.drop_index(op.f('ix_series_approvals_approver_name'), table_name='series_approvals')
    op.create_index(op.f('idx_user_id'), 'series_approvals', ['user_id'], unique=False)
    op.create_index(op.f('idx_series_id'), 'series_approvals', ['series_id'], unique=False)
    op.create_index(op.f('idx_series_action'), 'series_approvals', ['series_id', 'action_timestamp'], unique=False)
    op.create_index(op.f('idx_action_type'), 'series_approvals', ['action_type'], unique=False)
    op.create_index(op.f('idx_action_timestamp'), 'series_approvals', ['action_timestamp'], unique=False)
    op.drop_column('series_approvals', 'approved_at')
    op.drop_column('series_approvals', 'comments')
    op.drop_column('series_approvals', 'action')
    op.drop_column('series_approvals', 'approver_role')
    op.drop_column('series_approvals', 'approver_name')
    op.add_column('role_permissions', sa.Column('updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('role_permissions', sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('role_permissions', sa.Column('permissions', mysql.JSON(), nullable=False))
    op.drop_index(op.f('ix_role_permissions_role_name'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_name'), table_name='role_permissions')
    op.create_index(op.f('unique_role'), 'role_permissions', ['role'], unique=True)
    op.create_index(op.f('idx_updated_at'), 'role_permissions', ['updated_at'], unique=False)
    op.create_index(op.f('idx_role'), 'role_permissions', ['role'], unique=False)
    op.alter_column('role_permissions', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('role_permissions', 'is_granted')
    op.drop_column('role_permissions', 'permission_name')
    op.drop_column('role_permissions', 'role_name')
    op.add_column('report_logs', sa.Column('generation_time_ms', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_logs', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('report_logs', sa.Column('file_size_kb', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('report_logs', sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('report_logs', sa.Column('user_role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('report_logs', sa.Column('record_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('report_logs', sa.Column('report_filters', mysql.JSON(), nullable=True))
    op.create_foreign_key(op.f('report_logs_ibfk_1'), 'report_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_report_logs_report_type'), table_name='report_logs')
    op.drop_index(op.f('ix_report_logs_generated_by'), table_name='report_logs')
    op.drop_index(op.f('ix_report_logs_generated_at'), table_name='report_logs')
    op.create_index(op.f('idx_user_id'), 'report_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_date'), 'report_logs', ['user_id', 'generated_at'], unique=False)
    op.create_index(op.f('idx_status'), 'report_logs', ['status'], unique=False)
    op.create_index(op.f('idx_report_type'), 'report_logs', ['report_type'], unique=False)
    op.create_index(op.f('idx_report_name'), 'report_logs', ['report_name'], unique=False)
    op.create_index(op.f('idx_report_date'), 'report_logs', ['report_name', 'generated_at'], unique=False)
    op.create_index(op.f('idx_generated_at'), 'report_logs', ['generated_at'], unique=False)
    op.alter_column('report_logs', 'report_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('report_logs', 'report_type',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('PDF', 'Excel', 'CSV', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('report_logs', 'file_path')
    op.drop_column('report_logs', 'parameters')
    op.drop_column('report_logs', 'generated_by')
    op.add_column('ncd_series', sa.Column('last_modified_at', mysql.DATETIME(), nullable=True))
    op.add_column('ncd_series', sa.Column('rejected_at', mysql.DATETIME(), nullable=True))
    op.add_column('ncd_series', sa.Column('series_start_date', sa.DATE(), nullable=True))
    op.add_column('ncd_series', sa.Column('min_investment', mysql.DECIMAL(precision=20, scale=2), nullable=False))
    op.add_column('ncd_series', sa.Column('lock_in_date', sa.DATE(), nullable=True))
    op.add_column('ncd_series', sa.Column('last_modified_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ncd_series', sa.Column('release_date', sa.DATE(), nullable=False))
    op.add_column('ncd_series', sa.Column('rejection_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('ncd_series', sa.Column('min_subscription_percentage', mysql.DECIMAL(precision=20, scale=2), nullable=False))
    op.add_column('ncd_series', sa.Column('tenure', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('ncd_series', sa.Column('subscription_start_date', sa.DATE(), nullable=False))
    op.add_column('ncd_series', sa.Column('approval_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('ncd_series', sa.Column('rejected_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ncd_series', sa.Column('debenture_trustee_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('ncd_series', sa.Column('total_issue_size', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('ncd_series', sa.Column('target_amount', mysql.DECIMAL(precision=20, scale=2), nullable=False))
    op.add_column('ncd_series', sa.Column('subscription_end_date', sa.DATE(), nullable=False))
    op.add_column('ncd_series', sa.Column('interest_payment_day', mysql.INTEGER(), server_default=sa.text("'15'"), autoincrement=False, nullable=True, comment='Day of month when interest is paid (1-31)'))
    op.add_column('ncd_series', sa.Column('investors_size', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_approved_by'), 'ncd_series', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_last_modified_by'), 'ncd_series', 'users', ['last_modified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_rejected_by'), 'ncd_series', 'users', ['rejected_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ncd_series_status'), table_name='ncd_series')
    op.drop_index(op.f('ix_ncd_series_series_code'), table_name='ncd_series')
    op.drop_index(op.f('ix_ncd_series_maturity_date'), table_name='ncd_series')
    op.drop_index(op.f('ix_ncd_series_issue_date'), table_name='ncd_series')
    op.create_index(op.f('series_code'), 'ncd_series', ['series_code'], unique=True)
    op.create_index(op.f('name'), 'ncd_series', ['name'], unique=True)
    op.create_index(op.f('idx_status'), 'ncd_series', ['status'], unique=False)
    op.create_index(op.f('idx_series_code'), 'ncd_series', ['series_code'], unique=False)
    op.create_index(op.f('idx_is_active'), 'ncd_series', ['is_active'], unique=False)
    op.create_index(op.f('idx_dates'), 'ncd_series', ['issue_date', 'maturity_date', 'subscription_start_date', 'subscription_end_date', 'release_date'], unique=False)
    op.alter_column('ncd_series', 'approved_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('ncd_series', 'approved_by',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('ncd_series', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('ncd_series', 'credit_rating',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
    op.alter_column('ncd_series', 'security_type',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('Secured', 'Unsecured', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('ncd_series', 'status',
               existing_type=sa.Enum('draft', 'pending_approval', 'approved', 'active', 'matured', 'closed', name='seriesstatusenum'),
               type_=mysql.ENUM('DRAFT', 'REJECTED', 'upcoming', 'accepting', 'active', 'matured', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'DRAFT'"))
    op.alter_column('ncd_series', 'interest_frequency',
               existing_type=sa.Enum('Monthly', 'Quarterly', 'Half_Yearly', 'Yearly', name='interestfrequencyenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.alter_column('ncd_series', 'face_value',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=mysql.DECIMAL(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('ncd_series', 'interest_rate',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=mysql.DECIMAL(precision=20, scale=2),
               existing_nullable=False)
    op.drop_column('ncd_series', 'terms_conditions')
    op.drop_column('ncd_series', 'lock_in_period')
    op.drop_column('ncd_series', 'maximum_investment')
    op.drop_column('ncd_series', 'minimum_investment')
    op.drop_column('ncd_series', 'total_amount')
    op.add_column('investors', sa.Column('correspondence_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('investors', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('investors', sa.Column('occupation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('investors', sa.Column('source_of_funds', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('investors', sa.Column('nominee_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('investors', sa.Column('total_investment', mysql.DECIMAL(precision=15, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.add_column('investors', sa.Column('pan', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False))
    op.add_column('investors', sa.Column('residential_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('investors', sa.Column('nominee_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('investors', sa.Column('aadhaar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12), nullable=False))
    op.add_column('investors', sa.Column('date_joined', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('investors', sa.Column('nominee_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('investors', sa.Column('dob', sa.DATE(), nullable=False))
    op.add_column('investors', sa.Column('nominee_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('investors', sa.Column('nominee_relationship', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_index(op.f('ix_investors_status'), table_name='investors')
    op.drop_index(op.f('ix_investors_phone'), table_name='investors')
    op.drop_index(op.f('ix_investors_kyc_status'), table_name='investors')
    op.drop_index(op.f('ix_investors_investor_id'), table_name='investors')
    op.drop_index(op.f('ix_investors_email'), table_name='investors')
    op.create_index(op.f('investor_id'), 'investors', ['investor_id'], unique=True)
    op.create_index(op.f('idx_status'), 'investors', ['status'], unique=False)
    op.create_index(op.f('idx_kyc_status'), 'investors', ['kyc_status'], unique=False)
    op.create_index(op.f('idx_investor_id'), 'investors', ['investor_id'], unique=False)
    op.create_index(op.f('idx_email'), 'investors', ['email'], unique=False)
    op.alter_column('investors', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('investors', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investors', 'kyc_status',
               existing_type=sa.Enum('pending', 'verified', 'rejected', name='kycstatusenum'),
               type_=mysql.ENUM('Pending', 'Completed', 'Rejected', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
    op.alter_column('investors', 'ifsc_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               nullable=False)
    op.alter_column('investors', 'account_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('investors', 'bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('investors', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
    op.alter_column('investors', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('investors', 'created_by')
    op.drop_column('investors', 'account_holder_name')
    op.drop_column('investors', 'pincode')
    op.drop_column('investors', 'state')
    op.drop_column('investors', 'city')
    op.drop_column('investors', 'address')
    op.drop_column('investors', 'aadhar_number')
    op.drop_column('investors', 'pan_number')
    op.add_column('investor_series', sa.Column('first_investment_date', mysql.DATETIME(), nullable=True))
    op.add_column('investor_series', sa.Column('investment_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('investor_series', sa.Column('last_investment_date', mysql.DATETIME(), nullable=True))
    op.add_column('investor_series', sa.Column('total_invested', mysql.DECIMAL(precision=15, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.drop_index(op.f('ix_investor_series_status'), table_name='investor_series')
    op.drop_index(op.f('ix_investor_series_series_id'), table_name='investor_series')
    op.drop_index(op.f('ix_investor_series_investor_id'), table_name='investor_series')
    op.create_index(op.f('unique_investor_series'), 'investor_series', ['investor_id', 'series_id'], unique=True)
    op.create_index(op.f('idx_series_id'), 'investor_series', ['series_id'], unique=False)
    op.create_index(op.f('idx_investor_id'), 'investor_series', ['investor_id'], unique=False)
    op.alter_column('investor_series', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('investor_series', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investor_series', 'status',
               existing_type=sa.Enum('active', 'exited', 'matured', name='investorseriesstatusenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.drop_column('investor_series', 'exit_amount')
    op.drop_column('investor_series', 'exit_date')
    op.drop_index(op.f('ix_investor_documents_investor_id'), table_name='investor_documents')
    op.drop_index(op.f('ix_investor_documents_document_type'), table_name='investor_documents')
    op.create_index(op.f('idx_investor_id'), 'investor_documents', ['investor_id'], unique=False)
    op.create_index(op.f('idx_document_type'), 'investor_documents', ['document_type'], unique=False)
    op.alter_column('investor_documents', 'uploaded_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investor_documents', 'file_size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('investor_documents', 'uploaded_by')
    op.add_column('investments', sa.Column('exit_date', sa.DATE(), nullable=True, comment='Date when investor exited/withdrew from series'))
    op.add_column('investments', sa.Column('payment_document_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_series_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_investor_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_investment_date'), table_name='investments')
    op.create_index(op.f('idx_status'), 'investments', ['status'], unique=False)
    op.create_index(op.f('idx_series_id'), 'investments', ['series_id'], unique=False)
    op.create_index(op.f('idx_investor_id'), 'investments', ['investor_id'], unique=False)
    op.alter_column('investments', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('investments', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('investments', 'date_received',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('investments', 'date_transferred',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('investments', 'transaction_reference')
    op.drop_column('investments', 'payment_mode')
    op.drop_column('investments', 'investment_date')
    op.drop_column('investments', 'units')
    op.add_column('interest_payouts', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('interest_payouts', sa.Column('payout_month', mysql.VARCHAR(length=50), nullable=False, comment='e.g., February 2026'))
    op.add_column('interest_payouts', sa.Column('paid_date', sa.DATE(), nullable=True, comment='Actual date when payment was made'))
    op.create_table_comment(
        'interest_payouts',
        'Interest payout records for investors',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'interest_payouts', type_='foreignkey')
    op.drop_index(op.f('ix_interest_payouts_status'), table_name='interest_payouts')
    op.drop_index(op.f('ix_interest_payouts_series_id'), table_name='interest_payouts')
    op.drop_index(op.f('ix_interest_payouts_payout_date'), table_name='interest_payouts')
    op.drop_index(op.f('ix_interest_payouts_investor_id'), table_name='interest_payouts')
    op.create_index(op.f('unique_payout'), 'interest_payouts', ['investor_id', 'series_id', 'payout_month'], unique=True)
    op.create_index(op.f('idx_status'), 'interest_payouts', ['status'], unique=False)
    op.create_index(op.f('idx_series'), 'interest_payouts', ['series_id'], unique=False)
    op.create_index(op.f('idx_payout_month'), 'interest_payouts', ['payout_month'], unique=False)
    op.create_index(op.f('idx_investor'), 'interest_payouts', ['investor_id'], unique=False)
    op.alter_column('interest_payouts', 'status',
               existing_type=sa.Enum('pending', 'completed', 'failed', name='payoutstatusenum'),
               type_=mysql.ENUM('Paid', 'Pending', 'Scheduled'),
               existing_nullable=True,
               existing_server_default=sa.text("'Scheduled'"))
    op.alter_column('interest_payouts', 'amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='Interest amount in rupees',
               existing_nullable=False)
    op.alter_column('interest_payouts', 'payout_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               comment='e.g., 15-Feb-2026',
               existing_nullable=False)
    op.drop_column('interest_payouts', 'processed_at')
    op.drop_column('interest_payouts', 'processed_by')
    op.drop_column('interest_payouts', 'remarks')
    op.drop_column('interest_payouts', 'payment_reference')
    op.drop_column('interest_payouts', 'investment_id')
    op.add_column('grievances', sa.Column('series_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('grievances', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('grievances', sa.Column('trustee_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('grievances', sa.Column('resolution_comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('grievances', sa.Column('created_by_role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('grievances', sa.Column('investor_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('grievances', sa.Column('grievance_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.drop_constraint(None, 'grievances', type_='foreignkey')
    op.drop_constraint(None, 'grievances', type_='foreignkey')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_series_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_priority'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_investor_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_grievance_type'), table_name='grievances')
    op.create_index(op.f('idx_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('idx_series_id'), 'grievances', ['series_id'], unique=False)
    op.create_index(op.f('idx_priority'), 'grievances', ['priority'], unique=False)
    op.create_index(op.f('idx_investor_id'), 'grievances', ['investor_id'], unique=False)
    op.create_index(op.f('idx_grievance_type'), 'grievances', ['grievance_type'], unique=False)
    op.create_index(op.f('idx_created_at'), 'grievances', ['created_at'], unique=False)
    op.create_index(op.f('idx_category'), 'grievances', ['category'], unique=False)
    op.create_index(op.f('grievance_id'), 'grievances', ['grievance_id'], unique=True)
    op.alter_column('grievances', 'resolved_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('grievances', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('grievances', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('grievances', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('grievances', 'status',
               existing_type=sa.Enum('open', 'in_progress', 'resolved', 'closed', name='grievancestatusenum'),
               type_=mysql.ENUM('pending', 'in-progress', 'resolved', 'closed', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('grievances', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('grievances', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('grievances', 'investor_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.drop_column('grievances', 'assigned_to')
    op.drop_column('grievances', 'resolution')
    op.add_column('compliance_master_items', sa.Column('section', mysql.ENUM('pre', 'post', 'recurring', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('compliance_master_items', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.add_column('compliance_master_items', sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('compliance_master_items', sa.Column('legal_reference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), server_default=sa.text("'Internal Protocol'"), nullable=True))
    op.create_table_comment(
        'compliance_master_items',
        'Master template of 42 compliance items - shared across all series',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_compliance_master_items_frequency'), table_name='compliance_master_items')
    op.drop_index(op.f('ix_compliance_master_items_category'), table_name='compliance_master_items')
    op.create_index(op.f('idx_section'), 'compliance_master_items', ['section'], unique=False)
    op.create_index(op.f('idx_display_order'), 'compliance_master_items', ['display_order'], unique=False)
    op.create_index(op.f('idx_active'), 'compliance_master_items', ['is_active'], unique=False)
    op.alter_column('compliance_master_items', 'frequency',
               existing_type=sa.Enum('Monthly', 'Quarterly', 'Half_Yearly', 'Yearly', 'One_Time', name='compliancefrequencyenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.drop_column('compliance_master_items', 'updated_at')
    op.drop_column('compliance_master_items', 'category')
    op.drop_column('compliance_master_items', 'item_name')
    op.add_column('compliance_documents', sa.Column('deleted_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('compliance_documents', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('compliance_documents', sa.Column('deleted_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('compliance_documents', sa.Column('s3_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.add_column('compliance_documents', sa.Column('document_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('compliance_documents', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('compliance_documents', sa.Column('s3_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False))
    op.add_column('compliance_documents', sa.Column('master_item_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('compliance_documents', sa.Column('content_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('compliance_documents', sa.Column('s3_bucket', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('compliance_documents', sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('compliance_documents', sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'compliance_documents', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_documents_ibfk_2'), 'compliance_documents', 'compliance_master_items', ['master_item_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_compliance_documents_series_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_compliance_status_id'), table_name='compliance_documents')
    op.create_index(op.f('idx_uploaded_at'), 'compliance_documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('idx_series_category'), 'compliance_documents', ['series_id'], unique=False)
    op.create_index(op.f('idx_active'), 'compliance_documents', ['is_active'], unique=False)
    op.alter_column('compliance_documents', 'uploaded_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('compliance_documents', 'file_size',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('compliance_documents', 'file_path')
    op.drop_column('compliance_documents', 'compliance_status_id')
    op.drop_index(op.f('ix_communication_templates_type'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_is_active'), table_name='communication_templates')
    op.create_index(op.f('idx_type'), 'communication_templates', ['type'], unique=False)
    op.create_index(op.f('idx_active'), 'communication_templates', ['is_active'], unique=False)
    op.add_column('communication_history', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_communication_history_type'), table_name='communication_history')
    op.drop_index(op.f('ix_communication_history_status'), table_name='communication_history')
    op.drop_index(op.f('ix_communication_history_sent_at'), table_name='communication_history')
    op.drop_index(op.f('ix_communication_history_investor_id'), table_name='communication_history')
    op.create_index(op.f('idx_type'), 'communication_history', ['type'], unique=False)
    op.create_index(op.f('idx_status'), 'communication_history', ['status'], unique=False)
    op.create_index(op.f('idx_series_name'), 'communication_history', ['series_name'], unique=False)
    op.create_index(op.f('idx_sent_at'), 'communication_history', ['sent_at'], unique=False)
    op.create_index(op.f('idx_investor_id'), 'communication_history', ['investor_id'], unique=False)
    op.alter_column('communication_history', 'sent_by_role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.add_column('audit_logs', sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('idx_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('idx_admin_name'), 'audit_logs', ['admin_name'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('audit_logs', 'admin_role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
